### ISSUE TITLE
Create Trigger : inconsistencies in the count of volunteer

### ISSUE THREAD

**Issue by dev-mansonthomas** [minutis-redcall/app#340]
1. Create a Trigger
2. Choose whole Paris
3. PSE2 : 700, but the summary mention 673 nivol triggered, 2 without email, 4 without phone.  1 is missing.

Then if I add CH:  there's 674 people triggered, 2 without email, 4 without phone. : The number should not increase since a CH must be PSE2.
Then if I add CI :  677 people triggered, 2 without email, 4 without phone. : The number should not increase since a CI must be PSE2.

This can be a minor issue, but I just want to be sure there's not a bigger issue underneath. 

![image](https://user-images.githubusercontent.com/5695269/85788597-84581d80-b72d-11ea-9105-ab5d06513cb6.png)
![image](https://user-images.githubusercontent.com/5695269/85788633-933ed000-b72d-11ea-8a52-1599f223356c.png)
![image](https://user-images.githubusercontent.com/5695269/85788660-9d60ce80-b72d-11ea-942a-9a17d0389f9b.png)
![image](https://user-images.githubusercontent.com/5695269/85788683-a3ef4600-b72d-11ea-83b3-cc4e3e14ba38.png)
![image](https://user-images.githubusercontent.com/5695269/85788706-ac478100-b72d-11ea-868f-148fb87f4a01.png)
![image](https://user-images.githubusercontent.com/5695269/85788727-b36e8f00-b72d-11ea-99a4-e3e38137f198.png)

**Comment by ninsuo** [comment]
With the refactoring of the audience form, I've noticed that I used wrong counts.

To calculate the number of volunteers of a parent structure, I was doing the sum of the volunteers in the children structures. but it is wrong, because some volunteers (notably the ones from DTs) are tied to many of these structures and they were counted twice (or more).

This will be fixed in #491

**Comment by ninsuo** [comment]
#491
