### ISSUE TITLE
API: number-only values incorrectly rejected on string GET parameters

### ISSUE THREAD

**Issue by AmauryCarrade** [minutis-redcall/app#627]
Hello,

Playing with the API (thanks again), I noticed some weird `400 Bad Request` errors on apparently valid requests. It appears that parameters' type inference is way too strict.

All parameters in the API are typed, like, in the `Hello world` entry point, the `name` parameter type is `string`. But when we pass a GET parameter with a number-like value (lets say, `?name=128`), the type inference system reads it as an integer and the request is… rejected with a `400 Bad Request`, because the type is wrong (`int` is not `string`, right?).

### Example and expected response

As example, let's say I send this HTTP request:

```http
GET /api/demo?name=21 HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Bearer TOKEN
Connection: keep-alive
Host: rcl.re
User-Agent: HTTPie/2.5.0
X-Signature: SIGN
```

This is the response:

```http
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, private
Content-Length: 103
Content-Type: text/html; charset=UTF-8
Date: Wed, 29 Sep 2021 09:48:17 GMT
Server: Google Frontend
X-Cloud-Trace-Context: b209146f958fe319a28a4f288a685977

{
    "code": "0001",
    "context": [],
    "message": "An error occurred, check response status code.",
    "success": false
}
```

This should be the expected response:

```http
HTTP/1.1 200 OK
Cache-Control: no-cache, private
Content-Length: 103
Content-Type: text/html; charset=UTF-8
Date: Wed, 29 Sep 2021 09:50:06 GMT
Server: Google Frontend
X-Cloud-Trace-Context: ef94241edcf0679a6fb97e77f4508067

{
  "success": true,
  "payload": {
    "hello": "21"
  }
}
```

And as soon as I add a letter to the request parameter, everything work as intended:

```http
GET /api/demo?name=21B HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Bearer TOKEN
Connection: keep-alive
Host: rcl.re
User-Agent: HTTPie/2.5.0
X-Signature: SIGN


HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://rcl.re
Cache-Control: no-cache, private
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Wed, 29 Sep 2021 09:52:48 GMT
Server: Google Frontend
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Cloud-Trace-Context: 30fe1c268cbfe7c8d40c39520ac2db8b;o=1

{
    "payload": {
        "hello": "21B"
    },
    "success": true
}
```

### Implications

This is problematic because some Pegass records identifiers are numbers, so requests like `GET /api/admin/pegass?page=1&type=department&identifier=75` (to obtain the Parisian local units, just so I don't scan the whole list of volunteers) fail.

I tried to look at the source code but I don't really have experience with Sf4 (I used to work with Sf2 and Silex but that's pretty old now). This being said, if you have pointers, I would be happy to work on this myself.

Thank you very much!

**Comment by ninsuo** [comment]
Thank you Amaury,

During normalization, symfony serializer uses the `@var` annotations on the model object property in order to know whether the value is valid or not, in the demo case:

https://github.com/minutis-redcall/app/blob/master/symfony/bundles/api-bundle/Model/Facade/HelloRequestFacade.php#L16

But during the conversion of the query string into a flat json in order to map it to a model object, there's a type conversion on numeric values:

https://github.com/minutis-redcall/app/blob/master/symfony/bundles/api-bundle/ParamConverter/FacadeParamConverter.php#L37-L46

I need to find a way to only reject strings that do not contain numeric values when an integer is expected but a string value is given.

This issue only affects endpoints that use the `GET` verb.

**Comment by ninsuo** [comment]
Thank you Amaury,

During denormalization, symfony serializer uses the `@var` annotations on the model object property in order to know whether the value is valid or not, in the demo case:

https://github.com/minutis-redcall/app/blob/master/symfony/bundles/api-bundle/Model/Facade/HelloRequestFacade.php#L16

But during the conversion of the query string into a flat json in order to map it to a model object, there's a type conversion on numeric values:

https://github.com/minutis-redcall/app/blob/master/symfony/bundles/api-bundle/ParamConverter/FacadeParamConverter.php#L37-L46

A fix could be to allow `float` or `int` into the demo model object:

```
@var string|float
```

You may do that as a quick fix in the [Pegass model](https://github.com/minutis-redcall/app/blob/master/symfony/src/Facade/Pegass/PegassResourceFacade.php#L33) object. 

But it looks super verbose and quite not comfortable in the long run for all other model objects (ex: all "criteria" parameters in resource searches).

We better need to find a way to only reject strings that do not contain numeric values when an integer is expected but a string value is given.

**Comment by ninsuo** [comment]
I've found the root cause, parameters were [strong typed](https://github.com/minutis-redcall/app/blob/master/symfony/src/Facade/Pegass/PegassResourceFacade.php#L57) only leaving strings as a possible value for these properties.

Removing that strong typing (until Google App Engine supports PHP 8) is the solution.
I'm pushing a fix.

**Comment by ninsuo** [comment]
Found the right fix (later is better than never 😅 )
https://github.com/minutis-redcall/app/commit/51cb17b940b772537cb54ea1b2ee50c2e0cf6659

**Comment by AmauryCarrade** [comment]
Oh nice, thanks again!
